### ISSUE TITLE
unfollow keep_history argument change not mentioned in changelog

### ISSUE THREAD

**Issue by biinari** [GetStream/stream-ruby#130]
In version 4.0.0, the feed unfollow method signature changed from

```ruby
unfollow(target_feed_slug, target_user_id, keep_history = false)
```

to

```ruby
unfollow(target_feed_slug, target_user_id, keep_history: false)
```

Could the Changelog be retrospectively updated to mention this as a breaking change please?

gz#10769

**Comment by ferhatelmas** [comment]
`remove_activity` was also changed. [Added into changelog](https://github.com/GetStream/stream-ruby/blob/master/CHANGELOG.md#2020-11-18---400). Thanks for your attention.

**Comment by biinari** [comment]
Fantastic, thanks!
