### ISSUE TITLE
Batch activity partial update not working

### ISSUE THREAD

**Issue by MannanK** [GetStream/stream-ruby#131]
Hi, I was trying to use `batch_activity_partial_update` (as defined in #110 & [the docs](https://getstream.io/activity-feeds/docs/node/adding_activities/?language=python)) but keep getting an error that the URL doesn't exist:

```
...
...stream-ruby-4.1.0/lib/stream/client.rb:210:in `block in call': POST https://us-east-api.stream-io-api.com/api/v1.0/activity/?api_key=[REDACTED]: 404: url not found (Stream::StreamApiResponseException)
```

I really need to make use of this part of the API; any idea why this isn't working?

Thanks!

gz#11099

**Comment by shodgetts** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/11099'>Zendesk ticket #11099</a>:<br><br>Hi Mannan,
Sorry to hear about this issue. We will take a closer look to figure out why this is happening and let you know what we find.

Best,
-Cody

**Comment by MannanK** [comment]
Thanks @shodgetts

**Comment by MannanK** [comment]
Hi @shodgetts, I can't seem to get access to the Zendesk ticket, so I will update here.

The error seems to have been my fault, as the reason for it was none of the activities in the batch request existed (I thought I had created the activities already), thus resulting in the URL error. I'm testing it now after having created the activities and the endpoint is working.

That being said, I think there is room to make the error messages more specific & detailed, as all I was being told was the URL wasn't found, which led to me not realizing the cause for the error.

Anyhow, I shouldn't be needing any more help on this specifically at the moment, so I'll close the issue. Thanks!
