### ISSUE TITLE
Tests are not passing

### ISSUE THREAD

**Issue by volksport** [GetStream/stream-ruby#25]
Some tests are consistently failing (while others are inconsistently passing). Either the service is having inconsistencies/problems, or perhaps the lack of test tear downs/mocks is causing some of these failures?

Firstly, having one key/secret combo means that anyone running the tests simultaneously are creating race conditions that could potentially cause them to fail (depending on the current and future test logic).

Second, the overlap of feed keys makes this even more likely. You could start with randomized feed keys in the setup (while still using the live service), and completely remove all data from them during the teardown, which would make a collision less likely.

But ultimately, the library shouldn't be testing the actual API (they should have their own tests), it should be testing the input/output. That probably means mocking the actual API results (maybe even programmatically during the setup).

Just some thoughts...

-r

**Comment by tbarbugli** [comment]
Hi Robert,

You are right, when we first wrote the clients we wrote most of the test as
integration tests. Right now this does not make much sense for the reasons
you mentioned. A rewrite of the test suite is going to happen very soon :)
ᐧ

**Comment by rossta** [comment]
Thoughts on this? 

I tend to agree that we shouldn't be making API calls in typical test runs. You could use a library like [Webmock](https://github.com/bblimke/webmock) to set up the API responses as fixtures or a middle ground like [VCR](https://github.com/vcr/vcr) that would record actual API responses periodically (and each test would have its own setup and teardown recorded as well) so the majority of test runs would use mocks generated directly from the live api.
