### ISSUE TITLE
Getting "RequestTooLarge" on batch follow.

### ISSUE THREAD

**Issue by joshuairl** [GetStream/stream-ruby#26]
"{\"code\": 413, \"detail\": \"The request body was too large (limit is 128k)\", \"duration\": \"0ms\", \"exception\": \"RequestTooLarge\", \"status_code\": 413}"

Any tips?

**Comment by tbarbugli** [comment]
it seems like you are pushing too much data to the API endpoint. Could you
paste an example activity here?
ᐧ
