### ISSUE TITLE
Asynchronous HTTP client

### ISSUE THREAD

**Issue by kennym** [GetStream/stream-ruby#35]
Are there any plans on implementing an asynchronous HTTP client, as right now the client can be a real bottleneck in a web application if requests aren't moved into the background?

**Comment by kennym** [comment]
@tbarbugli @tschellenbach ^^^

**Comment by tbarbugli** [comment]
@kennym right now it should be fairly easy to move add and follow from the request to an async queue (eg. resque)

**Comment by kennym** [comment]
@tbarbugli yes, that sounds perfect. How would you do that with the Rails integration though? The only way I'd see that would be possible is by moving model creation/deletion into an async queue which is totally infeasible. We need a better way. Any ideas?

**Comment by kennym** [comment]
or are you talking about an async queue integration within this library? I think we could write an API to support popular ones like resque or sidekiq.

**Comment by tbarbugli** [comment]
model creation/deletion would stay in sync, it would be the feed manager to
run in the background via resque/sidekiq.

**Comment by kennym** [comment]
@tbarbugli ah, yes! I agree with your approach. Already working a PR ;-)
