### ISSUE TITLE
add support for JWT tokens

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-ruby#47]

**Comment by volksport** [comment]
@kennym have you tested that the tokens being generated are working for the REST API? The ones I'm generating with this ruby client are failing (if I replace the read token with the read/write token in Auth, it works fine).

```
$ curl -H "Authorization: zzzzzz0 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY" -X GET https://api.getstream.io/api/v1.0/feed/all_activity/0/?api_key=XXXXXX

{"code": null, "detail": "url signature missing or invalid", "duration": "5ms", "exception": "AuthenticationFailed", "status_code": 403}
```

**Comment by kennym** [comment]
@volksport the readonly token is for client-side usage only.

**Comment by tbarbugli** [comment]
@volksport when using the JWT for auth, you need to add an additional HTTP header

```
stream-auth-type=jwt
```
