### ISSUE TITLE
Able to loosen gem requirements?

### ISSUE THREAD

**Issue by leighhalliday** [GetStream/stream-ruby#73]
Are you able to allow faraday versions `>= 0.9`, and not limit `jwt` to exactly `1.5.2` (maybe allowing `>= 1.0`)? 

I've had to go back to to version `2.2.5` version of this gem to avoid jwt and faraday conflicts with other gems we are using.

**Comment by tbarbugli** [comment]
@iandouglas any ideas on this?

**Comment by leighhalliday** [comment]
@iandouglas @tbarbugli any updates on this?

will I run into issues using an older version of the gem?

**Comment by dwightgunning** [comment]
@iandouglas I suspect this resolved by PR #75 ?

**Comment by iandouglas** [comment]
@leighhalliday do you still need earlier versions of Faraday covered, or are you okay there?
