### ISSUE TITLE
Best way to initialize?

### ISSUE THREAD

**Issue by benjam1n** [GetStream/stream-ruby#74]
Hi there! This is probably a very newbie question but I searched like whole internet and can't figure it out. So, I have stream.rb in config/initializers with:
```ruby
require 'stream'
stream = Stream::Client.new(Rails.application.secrets.stream_key, Rails.application.secrets.stream_secret, Rails.application.secrets.stream_id, location: 'eu-central')
```
The problems is reaching this stream variable from controllers/models. Is there like a common practice on how to do this? I know this is probably simpler with stream-rails but it doesn't seem like its working with rails5 so I decided to go with ruby version.

**Comment by iandouglas** [comment]
@benjam1n I'd use something like `::Stream = Stream::Client...` but a better pattern would be putting it in your main ApplicationController and accessing from there, like `@stream = Stream::Client...` and having @stream scoped to any other controller. If you're also going to need it in the models, then the stream-rails gem will probably work better for you. (I'll be working on Rails 5 support in the very near future)
