### ISSUE TITLE
Batch follow example should be in separate hashes

### ISSUE THREAD

**Issue by gcwokeup** [GetStream/stream-ruby#78]
# Batch following many feeds (requires ruby 2.1 or later)
follows = [{
    :source => 'flat:1', :target => 'user:1',
    :source => 'flat:1', :target => 'user:2',
    :source => 'flat:1', :target => 'user:3'
}]

should be:
follows = [
    {:source => 'timeline:1', :target => 'user:1'},
    {:source => 'timeline:1', :target => 'user:2'},
    {:source => 'timeline:1', :target => 'user:3'}
]

Otherwise the keys will just get overwritten.

**Comment by iandouglas** [comment]
Thanks @gcwokeup all fixed.
