### ISSUE TITLE
Faraday middleware set after adapter

### ISSUE THREAD

**Issue by subdigital** [GetStream/stream-ruby#80]
Using the `stream-ruby` gem we're getting this in the logs:

> WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.

Looks like it's coming from here:

https://github.com/GetStream/stream-ruby/blob/7402dbc9ad15f8fd8776601ed26ebafec01f5233/lib/stream/client.rb#L145

**Comment by iandouglas** [comment]
@subdigital if you can suggest a workaround in a pull request I'd be happy to consider the change.

**Comment by subdigital** [comment]
Since this is a gem for a paid service, I do not think it is appropriate to ask your customers to send you pull-requests.

I pointed you to the exact line of the issue.  Moving that above the middleware is the fix. Right now every user of this gem will be showered with these log messages for every stream API call:

![image](https://user-images.githubusercontent.com/59140/33491481-09c9bc94-d680-11e7-9699-94ff87d747bc.png)

**Comment by iandouglas** [comment]
I understand your position. We do try to engage with our customers though and let them know that they're welcome to suggest changes at any time -- some customers have faster turnaround to submit a change than us prioritizing specific pieces of work.

I've published v2.5.10 of the gem to incorporate this change. Thanks for the suggestion.
