### ISSUE TITLE
Delete feed API does not exist

### ISSUE THREAD

**Issue by dtuite** [GetStream/stream-ruby#81]
The readme and gym support a `Feed#delete` method but I can't find it in [the docs](https://getstream.io/docs/) and it 404s.

```
Stream::StreamApiResponseException: DELETE https://eu-west-api.stream-io-api.com/api/v1.0/feed/gym/511/?api_key=[redacted]: 404: url not found
```

**Comment by iandouglas** [comment]
```
user_feed = client.feed('user':'dtuite')
user_feed.delete
```
Does this not work for you? The method is found here:

https://github.com/GetStream/stream-ruby/blob/b9bccca1ace8dcf77f608774d5cf659e1b02f7b9/lib/stream/feed.rb#L104-L109

**Comment by dtuite** [comment]
That's the method I was using. It 404s on the Stream API.

**Comment by rromanchuk** [comment]
@dtuite is it safe to assume the users notification feed will be destroyed with this call as well?

**Comment by JelteF** [comment]
Just to clear this up, at the moment there's no way to clean the contents of a feed.

**Comment by dotZoki** [comment]
This ticket is closed without any explanation. 
Deleting all feed content is not possible, DELETE method returns 404.
