### ISSUE TITLE
Need clarification on add to many

### ISSUE THREAD

**Issue by rromanchuk** [GetStream/stream-ruby#95]
Let's say we're in a game lobby, and i'm modeling  comment activity. Normally when a user would leave a comment i would add that activity to their user feed, and then utilize the `to:` field to add this activity to relevant users (in this scenario all users in the lobby). 

So now anyone following that user will see this story in their newsfeed, and those directly involved will also get the notifications. 

Now in some situations, i do not send this activity to the users feed because because of a privacy preference, so instead i take the activity and use the `add_to_many` (where as before i would attach it to the `to` field) and send them to the notification feeds, which is what i want. 

https://stackoverflow.com/questions/46435072/does-batch-activity-add-trigger-on-firehose

After reading this it looks like my notification firehose don't get these updates per design, although I still don't really get why. 

So instead of this: 

```ruby
to_array = push_users.pluck(:id).map {|id| "notification:#{id}" }
stream_client.add_to_many(activity_data, to_array)
```

I now have to do this in order to get the firehose. 

```ruby
push_users.pluck(:id).each do |id| 
  notification_feed = stream_client.feed('notification', id)  
  notification_feed.add_activity(activity_data)  
end
```

The problem is, I have decoupled my push logic and made the getstream firehose my clearing house for literal APN pushes, so any activity i want to push to multiple notification feeds has to be done individually, given that the activity cannot be added to the users feed.

**Comment by ruggi** [comment]
@rromanchuk as you correctly said, the Add to Many doesn't trigger the fanouts, so a solution here would be to use a separate feed for the privacy-enabled users and add the activity there with the `to` targets in order to correctly trigger firehose.
